name: Deploy Flutter Web

on:
  push:
    branches:
      - main # Срабатывает при пуше в ветку main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Получаем исходный код
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Устанавливаем Flutter
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      # 3. Собираем проект
      - name: Build Web
        run: |
          flutter pub get
          flutter build web --release --pwa-strategy=none

      # 4. Деплоим на сервер через rsync
      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-rlgoDzvc -i --delete"
          SOURCE: "build/web/" # Что копируем
          REMOTE_HOST: ${{ secrets.SERVER_HOST }}
          REMOTE_USER: ${{ secrets.SERVER_USER }}
          TARGET: "/var/www/flutter_grv" # Куда кладем на сервере
